# Generated by Django 5.1 on 2024-09-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_remove_file_file_file_box_file_name_file_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='box_file_id',
            new_name='box_file_id',
        ),
    ]
