# Generated by Django 5.1 on 2024-09-01 08:05

from django.db import migrations

def delete_all_file_rows(apps, schema_editor):
    File = apps.get_model('fileshare', 'File')
    File.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_all_file_rows),
    ]
