# Generated by Django 5.1 on 2024-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_auto_20240901_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='box_file_name',
            field=models.CharField(default='defult', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
