# Generated by Django 5.1 on 2024-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_news', '0003_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='small_img_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
